### ISSUE TITLE
What programming language should we use?

### ISSUE THREAD

**Issue by jeffwired** [USEPA/EPA_OMEGA_Model#1] opened 2019-04-19 14:19 UTC
The new EPA OSS policy:

[interim_oss_policy_final_0.pdf](https://github.com/USEPA/EPA_OMEGA_Model/files/3098348/interim_oss_policy_final_0.pdf)

This policy indicates that Open Source Software (OSS) should be used for new projects.

Please send along your suggestions for a decision on what language to use and why.

Thank you,

Jeff

**Comment by toddsherwood-EPA** [comment] 2019-04-19 15:33
My preference would be to work with Python since that's what I know best. But I'm not smart enough about speed differences and such to know how important the apparent speed advantage of C# would be to our project. I'm not worried much about Monte Carlo and uncertainty since I see those as once in a while runs and a very small part of what we'll do with OMEGA2.

That said, I'm open to whatever and will simply kick myself for not getting more involved with the C# dse code over that past year.

I did find this potential concern that says the bulk of C# ends up being paid rather than open source. Again, I don't know what we'd be missing with the FREE C#, maybe the text below is getting at MS Office, Windows, etc., which we obviously already have.

from https://www.slant.co/versus/110/115/~python_vs_c 
CON Often-used products in most C# development environments get expensive
The majority of the C# development community uses Microsoft products which are not all free and open-source. As you get into the enterprise level of some of these products and subscriptions, the expense is multiple factors of 10 greater.

While you can use a fully open-source and free C# environment, the community around that is much smaller. While this can be said for other languages as well, the majority of C# falls into the for-pay Microsoft realm.

**Comment by anthonyneam** [comment] 2019-04-22 12:59
I like writing in C++, but I am rusty in every language at this point.  I do think in data structures in C++ though.  I am not a fan of the data structures in Python.  They are not as straight forward as other languages.  Also, there is a definite speed concern with Python.  C++ is fast and easily supports structures like link lists using pointers.

**Comment by anthonyneam** [comment] 2019-04-22 15:28
GNU C++  https://gcc.gnu.org/projects/cxx-status.html

**Comment by kevinanewman** [comment] 2019-04-23 13:28
Here's the other main guiding document:

https://obamawhitehouse.archives.gov/sites/default/files/omb/memoranda/2016/m_16_21.pdf

**Comment by kevinanewman** [comment] 2019-04-23 15:04
Some Initial Thoughts on Programming Language Choices

Objectives
•	Language should be known to developers or relatively easy to learn
•	Language should be free and support cross-platform development
•	Language development tools (IDEs, etc) should be free, cross-platform and support individual developer’s personal preferences
•	Language should support some amount of auto-documentation
•	Language should support object-oriented programming
•	Language should have an open source community and easy access to open source packages or modules
•	Code products should be installable and runnable without requiring admin rights or the installation of runtime packages (.dlls, etc)
•	Language should support open-source GUI development, if desired
•	Language should support multi-core and multi-machine computing
•	Code development should be possible offline and not require an internet connection
•	Language should be as high-level a language as possible so developers can concentrate on algorithms and not bits, bytes and pointers
•	Code style guidelines should be well established and in wide use by the development community for that language

Thoughts on the DSE
•	A large portion of the DSE code deals with reading and writing Excel files
o	This is a waste of developer time
o	Excel files should be avoided, if at all possible
	Plaintext files (.txt, .csv) should be preferred
	Requires the end-user to have Microsoft Office / Excel installed, or possibly some Excel runtime
	Reading and writing Excel files is much slower than reading and writing plaintext files storing the equivalent data
•	A large portion of the DSE code implements generic container datatypes that are ultimately used to bin data by various attributes
o	Developing container datatypes is a waste of developer time when there are languages that natively support such types
o	The container classes are effectively workarounds for database-type queries which could be implemented in a much simpler and more straightforward fashion
•	It’s not clear (to me) that the C# code is cross-platform and not Windows-only
•	The current development environment (Visual Studio) requires a Microsoft account and intermittent online reactivation.  Are there other development environments for C# that don’t require Visual Studio?
•	A large portion of the code exists only to support the GUI
o	Only supports single, manually entered runs
o	Code to support “pumpkin spice” and related GUI preferences is a waste of developer time
o	A large portion of code to support very limited charts that also flip upside down and side to side is a waste of space and developer time

Thoughts on Python for OMEGA2
PROS
•	Language is known to some of the developers and should relatively easy to learn for new developers
•	Language is high-level and supports generic container classes natively
•	Here in the lab we are moving towards Python as a replacement for Matlab for data analysis purposes so the use of Python aligns with other Division goals
•	Language and development environments are free, run on all platforms (Windows, MacOS, Linux, etc) and some don’t require admin rights to install (WinPython, for example) and support offline or online coding
•	Multiple IDEs exist to suit developer preferences
•	Language supports code documentation in the form of “docstrings” that can be used to auto-generate documentation
•	There are a wide range of easily-accessible, free, open-source packages available that support almost every conceivable need, including cross-language support for things like R
o	Avoids reinventing the wheel and wasting developer time for commonly solved problems
•	Code products can be bundled as standalone executables (at least on Windows for sure) that don’t require any software to be installed or admin rights to run
•	Several GUI development options exist, including Tk and Qt
•	Multi-core and multi-machine computing is supported through a variety of open source packages
•	Language is high-level with only a few base datatypes and native support for generic container types
•	Code style guidelines are well established, used widely by the developer community (e.g. PEP-8, https://www.python.org/dev/peps/pep-0008/) and may be supported directly in the IDE (PyCharm, for example)
•	Language can integrate with other languages (C, etc) if required or desired

CONS
•	Might run slower than a compiled language
o	There are a few compiler options available that may speed execution if desired
o	Overall development and deploy time may be shorter
•	Using open-source packages can lead to using open-source bugs
o	Would require solid regression-testing procedures, which we should be developing anyway
o	Would require careful integration of package updates or the clear definition of which package versions are officially sanctioned and tested
•	Not everyone on the developer team is familiar with Python
o	There is probably no single language that everyone is equally familiar with, no matter what the choice
o	Python seems relatively easy to learn and there are significant online resources available as well as formal trainings that could be provided if necessary

Thoughts in general
•	Anything a computer can do, a computer can do in any language, even binary, it’s mainly a question of development time and effort
•	There are many possible language choices, each with their own sets of pros and cons, no one language is ideal
•	Other development teams, such as the MOVES team, no doubt have insight into good programming practices and the management of large software projects so we should find out what others know that we don’t

**Closed** 2019-07-22 15:21 UTC
Labels: Big Picture
